package exercise2;

//@author: Ayesha Mohammed Azim Shaikh
//Student ID: 301166757

import javax.swing.*;

public class LottoDriver {
    public static void main(String[] args) {
        Lotto lotto = new Lotto();
        int[] arrayGenerated = lotto.getGeneratedArray();
        int sumOfArrayNumbers = 0;

        JOptionPane.showMessageDialog(null, "Welcome to the Lotto game! \n You are required to guess a number " +
                "generated by the computer which is between 3 and 27. You will be given 5 chances to guess the right " +
                "answer \n Simultaneously, the computer will generate 3 numbers between 1 to 9 and " +
                "calculate " +
                "their sum. If any of the choices made by you are equal to the sum generated by the computer, You " +
                "Win! \nIf not, then the computer wins. \n Lets Begin! Good Luck!");

        for (int i = 0; i < arrayGenerated.length; i++) {
            sumOfArrayNumbers = sumOfArrayNumbers + arrayGenerated[i];
        }
        int inputNumber = 0;
        boolean win = false;
        System.out.print(sumOfArrayNumbers);

        for (int i = 1; i < 6; i++) {
            if (i== 1) {
                inputNumber = Integer.parseInt(JOptionPane.showInputDialog("Please make your first guess."));
                while (inputNumber < 3 || inputNumber > 27) {
                    JOptionPane.showMessageDialog(null, "The number entered by  you is incorrect! YOU ARE REQUIRED TO " +
                            "ENTER A NUMBER BETWEEN 3 AND 27");
                    inputNumber = Integer.parseInt(JOptionPane.showInputDialog("Please enter a valid number! "));
                }
                if (inputNumber == sumOfArrayNumbers) {
                    JOptionPane.showMessageDialog(null, "Congratulations! You win.");
                    win = true;
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "Please try again.");
                }
            }
            if (i== 2) {
                inputNumber = Integer.parseInt(JOptionPane.showInputDialog("Please make your second guess."));
                while (inputNumber < 3 || inputNumber > 27) {
                    JOptionPane.showMessageDialog(null, "The number entered by  you is incorrect! YOU ARE REQUIRED TO " +
                            "ENTER A NUMBER BETWEEN 3 AND 27");
                    inputNumber = Integer.parseInt(JOptionPane.showInputDialog("Please enter a valid number! "));
                }
                if (inputNumber == sumOfArrayNumbers) {
                    JOptionPane.showMessageDialog(null, "Congratulations! You win.");
                    win = true;
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "Please try again.");
                }
            }
            if (i== 3) {
                inputNumber = Integer.parseInt(JOptionPane.showInputDialog("Keep going! This is your third guess."));
                while (inputNumber < 3 || inputNumber > 27) {
                    JOptionPane.showMessageDialog(null, "The number entered by  you is incorrect! YOU ARE REQUIRED TO " +
                            "ENTER A NUMBER BETWEEN 3 AND 27");
                    inputNumber = Integer.parseInt(JOptionPane.showInputDialog("Please enter a valid number! "));
                }
                if (inputNumber == sumOfArrayNumbers) {
                    JOptionPane.showMessageDialog(null, "Congratulations! You win.");
                    win = true;
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "Please try again.");
                }
            }
            if (i== 4) {
                inputNumber = Integer.parseInt(JOptionPane.showInputDialog("Put in your 4th guess."));
                while (inputNumber < 3 || inputNumber > 27) {
                    JOptionPane.showMessageDialog(null, "The number entered by  you is incorrect! YOU ARE REQUIRED TO " +
                            "ENTER A NUMBER BETWEEN 3 AND 27");
                    inputNumber = Integer.parseInt(JOptionPane.showInputDialog("Please enter a valid number! "));
                }
                if (inputNumber == sumOfArrayNumbers) {
                    JOptionPane.showMessageDialog(null, "Congratulations! You win.");
                    win = true;
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "Please try again.");
                }
            }
            if (i== 5) {
                inputNumber = Integer.parseInt(JOptionPane.showInputDialog("Last chance to win! Good Luck!"));
                while (inputNumber < 3 || inputNumber > 27) {
                    JOptionPane.showMessageDialog(null, "The number entered by  you is incorrect! YOU ARE REQUIRED TO " +
                            "ENTER A NUMBER BETWEEN 3 AND 27");
                    inputNumber = Integer.parseInt(JOptionPane.showInputDialog("Please enter a valid number! "));
                }
                if (inputNumber == sumOfArrayNumbers) {
                    JOptionPane.showMessageDialog(null, "Congratulations! You win.");
                    win = true;
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "Please try again.");
                }
            }

        }

        if (!win) {
            JOptionPane.showMessageDialog(null, "Computer wins! Better luck next time :(.");
        }
    }
}