package exercise2;

//@author: Ayesha Mohammed Azim Shaikh
//Student ID: 301166757

import java.util.Random;

public class Lotto {
    private int[] generatedArray; //stores int values generated by the computer
    public Lotto()
    {
        Random random=new Random();
        generatedArray=new int[3];

        //generates random number from 1 to 9
        generatedArray[0]=random.nextInt(9)+1;
        generatedArray[1]=random.nextInt(9)+1;
        generatedArray[2]=random.nextInt(9)+1;
    }
    // getter to return array generated by computer
    public int[] getGeneratedArray(){
        return generatedArray;
    }
}

